[global]
  target = "~/.local/eget/bin"
  upgrade_only = true

["terraform-linters/tflint"]

["noahgorstein/jqp"]

["junegunn/fzf"]

["ajeetdsouza/zoxide"]

["sxyazi/yazi"]

["BurntSushi/ripgrep"]

["ClementTsang/bottom"]
  file = "btm"
