[global]
  target = "~/.local/eget/bin"
  upgrade_only = true

["terraform-linters/tflint"]

["noahgorstein/jqp"]

["junegunn/fzf"]

["ajeetdsouza/zoxide"]

["sxyazi/yazi"]

["BurntSushi/ripgrep"]
  target = "~/.local/eget/bin/rg"

["ClementTsang/bottom"]
  asset_filters = [ "^gnu" ]
  file = "btm"
  target = "~/.local/eget/bin/btm"

["derailed/k9s"]
  asset_filters = [ "^json", "^deb", "^rpm", "^apk" ]

["sharkdp/bat"]
  asset_filters = [ "^musl", "^deb" ]

["jqlang/jq"]
  asset_filters = [ "{{.Arch}}" ]

["neovim/neovim"]
  asset_filters = [ "^appimage" ]
  file = "all"
