[global]
  target = "~/.local/eget/bin"
  upgrade_only = true

["terraform-linters/tflint"]

["noahgorstein/jqp"]

["junegunn/fzf"]

["ajeetdsouza/zoxide"]

["sxyazi/yazi"]

["BurntSushi/ripgrep"]
  target = "~/.local/eget/bin/rg"

["ClementTsang/bottom"]
  asset_filters = [ "^gnu" ]
  file = "btm"
  target = "~/.local/eget/bin/btm"

["derailed/k9s"]
  asset_filters = [ "^json", "^deb", "^rpm", "^apk" ]

["sharkdp/bat"]
  asset_filters = [ "^musl", "^deb" ]

["jqlang/jq"]
  asset_filters = [ "{{.Arch}}" ]

["neovim/neovim"]
  asset_filters = [ "^appimage" ]
  file = "nvim*/*"
  all = true
  target = "~/.local/eget/bin/nvim"
  binary = "~/.local/eget/bin/nvim/bin/nvim"

["opentofu/opentofu"]
  asset_filters = [ "{{.OS}}_{{.Arch}}.tar.gz", "^.gpgsig", "^.pem", "^.sig" ]
  file = "tofu"
  target = "~/.local/eget/bin/tofu"

["sharkdp/fd"]

["dandavison/delta"]

["jesseduffield/lazygit"]

["antonmedv/fx"]

["charmbracelet/glow"]
  asset_filters = [ "^json", ]

["charmbracelet/freeze"]
  asset_filters = [ "^json", ]

["charmbracelet/gum"]
  asset_filters = [ "^json", ]

["charmbracelet/mods"]
  asset_filters = [ "^json", ]

["pulumi/pulumi"]
  asset_filters = [ "^sig", ]
  all = true
  binary = "~/.local/eget/bin/pulumi"

["zaproxy/zaproxy"]
